# typed: false
# frozen_string_literal: true

# This file was generated by bulle's release workflow. DO NOT EDIT.
class Bulle < Formula
  desc "Run developer tools in a sandbox"
  homepage "https://github.com/vincentarelbundock/bulle"
  url "https://github.com/vincentarelbundock/bulle/archive/refs/tags/v0.0.4.tar.gz"
  sha256 "c506998ebb5bfd23e73d1475743a7e9aaffa0af5b3a737a56a3d97b5e8fd13e1"
  license "MIT"

  depends_on "go" => :build

  def install
    ENV["CGO_ENABLED"] = "0"
    ldflags = "-s -w -X github.com/vincentarelbundock/bulle/internal/app.Version=#{version}"
    system "go", "build", "-ldflags", ldflags, "-o", bin/"bulle", "./cmd/bulle"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bulle --version")
  end
end
