# typed: false
# frozen_string_literal: true

# This file was generated by bulle's release workflow. DO NOT EDIT.
class Bulle < Formula
  desc "Run developer tools in a sandbox"
  homepage "https://github.com/vincentarelbundock/bulle"
  url "https://github.com/vincentarelbundock/bulle/archive/refs/tags/v0.0.2.tar.gz"
  sha256 "6903361fb6729334f2ac57a978ccb4f33abe346970a813687fcf05385e796cf7"
  license "MIT"

  depends_on "go" => :build

  def install
    ENV["CGO_ENABLED"] = "0"
    ldflags = "-s -w -X github.com/vincentarelbundock/bulle/internal/app.Version=#{version}"
    system "go", "build", "-ldflags", ldflags, "-o", bin/"bulle", "./cmd/bulle"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bulle --version")
  end
end
