# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bulle < Formula
  desc "Run developer tools in a sandbox"
  homepage "https://github.com/vincentarelbundock/bulle"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vincentarelbundock/bulle/releases/download/v0.0.1/bulle_Darwin_x86_64.tar.gz"
      sha256 "66a0edbad4c929c3bdb0c81f42cdcad944b78a540272fdc6f32efa244d166fd9"

      define_method(:install) do
        bin.install "bulle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vincentarelbundock/bulle/releases/download/v0.0.1/bulle_Darwin_arm64.tar.gz"
      sha256 "98230c49306f3859d5c8b5893af13e914f2f039b3ea13297e2eeba63ffdafd09"

      define_method(:install) do
        bin.install "bulle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincentarelbundock/bulle/releases/download/v0.0.1/bulle_Linux_x86_64.tar.gz"
      sha256 "6889c080a468eb97e7c4a1e9129036099ab324b9e8b43a45d6d11ebc0f03c95b"
      define_method(:install) do
        bin.install "bulle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vincentarelbundock/bulle/releases/download/v0.0.1/bulle_Linux_arm64.tar.gz"
      sha256 "4c8abee63aa306b36be1ba3751a35d48560884bdf26ca11ed68041b54398c291"
      define_method(:install) do
        bin.install "bulle"
      end
    end
  end

  test do
    system "#{bin}/bulle", "--version"
  end
end
