# typed: false
# frozen_string_literal: true

# This file was generated by calepin's release workflow. DO NOT EDIT.
class Calepin < Formula
  desc "Preprocess Typst documents with executable code chunks"
  homepage "https://github.com/vincentarelbundock/calepin"
  url "https://github.com/vincentarelbundock/calepin/archive/refs/tags/v0.0.55.tar.gz"
  sha256 "380466cb9a6cdb20ecb712742a8b895eba5706291ad4fec5d0ffd81d43466e9f"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", "--path", ".", "--root", prefix, "--bin", "calepin"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/calepin --version")
  end
end
