# typed: false
# frozen_string_literal: true

# This file was generated by calepin's release workflow. DO NOT EDIT.
class Calepin < Formula
  desc "Preprocess Typst documents with executable code chunks"
  homepage "https://github.com/vincentarelbundock/calepin"
  url "https://github.com/vincentarelbundock/calepin/archive/refs/tags/v0.0.49.tar.gz"
  sha256 "db236f8d9b83fb361673c53e04846f1d73cc320a13e7ce1f64fc0fd68997794b"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", "--path", ".", "--root", prefix, "--bin", "calepin"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/calepin --version")
  end
end
