# typed: false
# frozen_string_literal: true

# This file was generated by calepin's release workflow. DO NOT EDIT.
class Calepin < Formula
  desc "Preprocess Typst documents with executable code chunks"
  homepage "https://github.com/vincentarelbundock/calepin"
  url "https://github.com/vincentarelbundock/calepin/archive/refs/tags/v0.0.45.tar.gz"
  sha256 "fedd3216ffdc88edcc21a4de2815c1be187512b7f551e2dcfe0c8ebb04a3e561"
  license "MIT"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--locked", "--path", ".", "--root", prefix, "--bin", "calepin"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/calepin --version")
  end
end
