# typed: false
# frozen_string_literal: true

# This file is generated by LibrePaper's release workflow. DO NOT EDIT.
class Librepaper < Formula
  desc "Browser based document collaboration and review companion"
  homepage "https://github.com/LibrePaper/librepaper"
  version "0.0.28"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/LibrePaper/librepaper/releases/download/v0.0.28/librepaper-aarch64-apple-darwin.tar.xz"
      sha256 "4579901c77b98ce0d1f80b84d5d5b09aa3b3b2337d7c3fc569ce2471d6541a60"
    end
    on_intel do
      url "https://github.com/LibrePaper/librepaper/releases/download/v0.0.28/librepaper-x86_64-apple-darwin.tar.xz"
      sha256 "c91dcef0449e5ad8ec124bce9ceee08b34c44b5de2f7bdb6d317839919e18bd4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/LibrePaper/librepaper/releases/download/v0.0.28/librepaper-aarch64-unknown-linux-musl.tar.xz"
      sha256 "0a06b22f418f4be596f38325a3d31b40ef8e0a4edaac929b6eb562518b30ae8b"
    end
    on_intel do
      url "https://github.com/LibrePaper/librepaper/releases/download/v0.0.28/librepaper-x86_64-unknown-linux-musl.tar.xz"
      sha256 "68e82dfc97cda38c5a32e147d8a86db1a4b47f37b14a26bab05f0e4e63a3a6c8"
    end
  end

  def install
    bin.install "librepaper"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/librepaper --version")
  end
end
